#!/usr/bin/env bash
# Machine discovery — gathers system info and writes knowledge/topics/machine.md
# Usage: relaygent discover [--json]
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib.sh"
load_config_soft

JSON_MODE=false
[[ "${1:-}" == "--json" ]] && JSON_MODE=true

KB_DIR="${KB_DIR:-$(dirname "$SCRIPT_DIR")/../../knowledge/topics}"
OUT="$KB_DIR/machine.md"
TODAY=$(date +%Y-%m-%d)

# --- Gather info ---
HOST=$(hostname -s 2>/dev/null || hostname)
OS=$(uname -s)
ARCH=$(uname -m)
if [[ "$OS" == "Darwin" ]]; then
    OS_VER="macOS $(sw_vers -productVersion 2>/dev/null || echo '?')"
    CPU=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "?")
    RAM="$(( $(sysctl -n hw.memsize 2>/dev/null || echo 0) / 1073741824 ))GB"
    DISK_TOTAL="$(df -g ~ 2>/dev/null | awk 'NR==2{print $2}')GB"
    DISK_USED=$(df -g ~ 2>/dev/null | awk 'NR==2{print $5}')
    SHELL_NAME=$(basename "$SHELL")
elif [[ "$OS" == "Linux" ]]; then
    OS_VER=$(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME" || echo "Linux")
    CPU=$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2 | xargs || echo "?")
    RAM="$(free -g 2>/dev/null | awk '/Mem:/{print $2}')GB"
    DISK_TOTAL=$(df -BG ~ 2>/dev/null | awk 'NR==2{print $2}')
    DISK_USED=$(df -BG ~ 2>/dev/null | awk 'NR==2{print $5}')
    SHELL_NAME=$(basename "${SHELL:-bash}")
else
    OS_VER="$OS $(uname -r)"; CPU="?"; RAM="?"; DISK_TOTAL="?"; DISK_USED="?"; SHELL_NAME="sh"
fi

# Languages — use parallel arrays (bash 3.2 compat, no associative arrays)
LANG_NAMES=(); LANG_VERS=()
detect_lang() {
    local cmd="$1" ver=""
    command -v "$cmd" &>/dev/null || return 0
    case "$cmd" in
        python3) ver=$(python3 --version 2>&1 | awk '{print $2}') ;;
        node)    ver=$(node -v 2>/dev/null | tr -d v) ;;
        go)      ver=$(go version 2>/dev/null | awk '{print $3}' | tr -d go) ;;
        rustc)   ver=$(rustc --version 2>/dev/null | awk '{print $2}') ;;
        *)       ver=$("$cmd" --version 2>&1 | head -1 | grep -oE '[0-9]+\.[0-9.]+' | head -1 || true) ;;
    esac
    LANG_NAMES+=("$cmd"); LANG_VERS+=("${ver:-?}")
}
for cmd in python3 node ruby go rustc java gcc g++ swift php perl; do detect_lang "$cmd"; done

# Package managers
PKGMGRS=()
for pm in brew apt dnf yum pacman nix npm yarn pnpm pip pip3 cargo gem; do
    command -v "$pm" &>/dev/null && PKGMGRS+=("$pm")
done

# Key tools
TOOLS=()
for tool in git docker kubectl terraform ansible make cmake tmux vim nvim emacs code cursor; do
    command -v "$tool" &>/dev/null && TOOLS+=("$tool")
done

# Network
TAILSCALE_IP=""
command -v tailscale &>/dev/null && TAILSCALE_IP=$(tailscale ip -4 2>/dev/null || true)

# Git repos in common dirs
REPOS=()
for dir in ~/projects ~/repos ~/src ~/code ~/work ~; do
    [[ -d "$dir" ]] || continue
    while IFS= read -r repo; do
        REPOS+=("$(basename "$(dirname "$repo")")")
    done < <(find "$dir" -maxdepth 2 -name .git -type d 2>/dev/null | head -20)
done
# Deduplicate
if [[ ${#REPOS[@]} -gt 0 ]]; then
    REPOS=($(printf '%s\n' "${REPOS[@]}" | sort -u))
fi

# --- JSON output ---
if $JSON_MODE; then
    lang_json=""
    for i in "${!LANG_NAMES[@]}"; do
        [[ -n "$lang_json" ]] && lang_json+=","
        lang_json+="\"${LANG_NAMES[$i]}\":\"${LANG_VERS[$i]}\""
    done
    to_json_arr() { local out=""; for v in "$@"; do [[ -n "$out" ]] && out+=","; out+="\"$v\""; done; echo "$out"; }
    echo "{\"host\":\"$HOST\",\"os\":\"$OS_VER\",\"arch\":\"$ARCH\",\"cpu\":\"$CPU\",\"ram\":\"$RAM\",\"disk_used\":\"$DISK_USED\",\"shell\":\"$SHELL_NAME\",\"tailscale\":\"$TAILSCALE_IP\",\"languages\":{${lang_json}},\"tools\":[$(to_json_arr "${TOOLS[@]}")],\"package_managers\":[$(to_json_arr "${PKGMGRS[@]}")],\"repos\":[$(to_json_arr "${REPOS[@]}")]}"
    exit 0
fi

# --- Write KB topic ---
{
cat <<HEADER
---
title: Machine — $HOST
created: $TODAY
updated: $TODAY
tags: [system, machine]
---

# Machine: $HOST

Auto-generated by \`relaygent discover\`. Re-run to update.

## System

| | |
|---|---|
| OS | $OS_VER ($ARCH) |
| CPU | $CPU |
| RAM | $RAM |
| Disk | $DISK_TOTAL total, $DISK_USED used |
| Shell | $SHELL_NAME |
HEADER

[[ -n "$TAILSCALE_IP" ]] && echo "| Tailscale | (configured) |"

echo -e "\n## Languages\n"
if [[ ${#LANG_NAMES[@]} -gt 0 ]]; then
    for i in "${!LANG_NAMES[@]}"; do echo "- **${LANG_NAMES[$i]}** ${LANG_VERS[$i]}"; done
else
    echo "- None detected"
fi

echo -e "\n## Package Managers\n"
echo "${PKGMGRS[*]:-none detected}"

echo -e "\n## Tools\n"
echo "${TOOLS[*]:-none detected}"

if [[ ${#REPOS[@]} -gt 0 ]]; then
    echo -e "\n## Git Repos\n"
    for r in "${REPOS[@]}"; do echo "- $r"; done
fi
} > "$OUT"

echo "Machine info written to $OUT"
echo "  Host: $HOST ($OS_VER, $ARCH)"
echo "  Languages: ${LANG_NAMES[*]:-none}"
echo "  Tools: ${TOOLS[*]:-none}"
[[ ${#REPOS[@]} -gt 0 ]] && echo "  Repos: ${REPOS[*]}"
